[package]
name = "gameplay"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy.workspace = true
bevy_rapier3d = { version = "0.25.0", features = ["dim3"] }
