[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy.workspace = true
world.workspace = true
gameplay = { path = "../gameplay" }
bevy_rapier3d = { version = "0.25.0", features = ["dim3"] }
